#ifndef COMPILADORES_PRACTICA1_ANALIZADOR_SINTACTICO_H
#define COMPILADORES_PRACTICA1_ANALIZADOR_SINTACTICO_H

void ejecutar_analizador();

#endif //COMPILADORES_PRACTICA1_ANALIZADOR_SINTACTICO_H
