
#ifndef COMPILADORES_PRACTICA1_DEFINICIONES_H
#define COMPILADORES_PRACTICA1_DEFINICIONES_H

//CODIGOS DE LOS COMPONENTES LEXICOS
#define IMPORT 300
#define DOUBLE 301
#define INT 302
#define WHILE 303
#define RETURN 304
#define VOID 305
#define FOREACH 306
#define ID 307
#define STRING 308
#define OPERADOR_MAS_MAS 309
#define OPERADOR_MAS_IGUAL 310
#define OPERADOR_MENOS_MENOS 311
#define OPERADOR_MENOS_IGUAL 312
#define OPERADOR_IGUAL_IGUAL 313
#define OPERADOR_POR_IGUAL 314
#define OPERADOR_ENTRE_IGUAL 315
#define INTEGER_LITERAL 316
#define FLOATING_POINT_LITERAL 317

#endif //COMPILADORES_PRACTICA1_DEFINICIONES_H
